### Register a user
POST https://api.to.wtf/register
content-type: application/json

{
    "first_name": "Michael",
    "last_name": "Preston",
    "phone": "+18175652372",
    "email": "demoday@gmail.com",
    "password": "daef4953b9783365cad6615223720506cc46c5167cd16ab500fa597aa08ff964eb24fb19687f34d7665f778fcb6c5358fc0a5b81e1662cf90f73a2671c53f991",
    "address": "105 Bleecker St.",
    "city": "Brookln",
    "pic_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTw3dxAr-998XQnx4i8BeI2Gk3AUo2U-Wu7MO3nPTqIFIB2btxL",
    "location": {
        "lat": 40.650002,
        "lng": -73.949997
    },
    "paragraph": "Perferendis aut sit voluptatem consequatur accusantium. Accusantium sit perferendis consequatur voluptatem aut. Voluptatem accusantium consequatur sit aut perferendis.",
    "offers": "good company & much more",
    "country": "United States of America"
}

### Login
POST https://api.to.wtf/login
content-type: application/json

{
    "email": "michael.n.preston@gmail.com",
    "password": "daef4953b9783365cad6615223720506cc46c5167cd16ab500fa597aa08ff964eb24fb19687f34d7665f778fcb6c5358fc0a5b81e1662cf90f73a2671c53f991"
}

### Get All Users
GET https://api.to.wtf/users

### Get User by ID
GET https://api.to.wtf/u/5df50025dbd9bd77fd966b9f

